"use client";

import { useState, use } from "react";
import Link from "next/link";
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, LineChart, Line,
} from "recharts";
import {
  Github, ExternalLink, Shield, AlertTriangle, Lock, Check,
  TrendingUp, TrendingDown, Share2
} from "lucide-react";
import { DashboardNav } from "@/components/dashboard/nav";
import { STARTUPS, fmt } from "@/lib/mock-data";

const PIE_COLORS = ["#1a1a1a", "#555", "#999", "#ccc"];
const SOCIAL_DATA = [
  { month: "Aug", followers: 340, mentions: 18 },
  { month: "Sep", followers: 520, mentions: 32 },
  { month: "Oct", followers: 710, mentions: 44 },
  { month: "Nov", followers: 980, mentions: 71 },
  { month: "Dec", followers: 1230, mentions: 58 },
  { month: "Jan", followers: 1580, mentions: 92 },
  { month: "Feb", followers: 2010, mentions: 115 },
  { month: "Mar", followers: 2480, mentions: 138 },
];

export default function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const startup = STARTUPS.find((s) => s.id === id) ?? STARTUPS[0];
  const [unlocked, setUnlocked] = useState(false);
  const [paying, setPaying] = useState(false);
  const [copied, setCopied] = useState(false);

  function handleUnlock() {
    setPaying(true);
    setTimeout(() => {
      setPaying(false);
      setUnlocked(true);
    }, 1800);
  }

  function handleCopy() {
    navigator.clipboard.writeText(window.location.href).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const langData = Object.entries(startup.languages).map(([name, pct]) => ({
    name, value: pct,
  }));

  const valRange = {
    low: startup.valuationCap * 0.7,
    mid: startup.valuationCap,
    high: startup.valuationCap * 1.4,
  };

  return (
    <div className="min-h-screen bg-background">
      <DashboardNav />

      <div className="max-w-5xl mx-auto px-6 pt-36 pb-8">
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
          <Link href="/" className="hover:text-foreground transition-colors">Markets</Link>
          <span>/</span>
          <Link href={`/market/${startup.id}`} className="hover:text-foreground transition-colors">{startup.name}</Link>
          <span>/</span>
          <span className="text-foreground">Full report</span>
        </div>

        {/* Header */}
        <div className="flex items-start justify-between gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-display mb-1">{startup.name} — AI Report</h1>
            <p className="text-sm text-muted-foreground">
              Generated by PublicRound AI Agent · {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
            </p>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs border border-foreground/20 px-3 py-1.5 hover:bg-foreground/5 transition-colors"
            >
              <Share2 className="w-3.5 h-3.5" />
              {copied ? "Copied!" : "Share"}
            </button>
            <Link
              href={`/market/${startup.id}`}
              className="flex items-center gap-1.5 text-xs border border-foreground/20 px-3 py-1.5 hover:bg-foreground/5 transition-colors"
            >
              <ExternalLink className="w-3.5 h-3.5" /> Market page
            </Link>
          </div>
        </div>

        {/* Summary scores (always visible) */}
        <div className="grid sm:grid-cols-5 gap-3 mb-8">
          {[
            { label: "Overall", value: startup.scores.overall },
            { label: "Code", value: startup.scores.codeQuality },
            { label: "Team", value: startup.scores.team },
            { label: "Traction", value: startup.scores.traction },
            { label: "Social", value: startup.scores.social },
          ].map((s) => (
            <div key={s.label} className="border border-foreground/10 p-4 text-center">
              <p className="text-3xl font-display mb-1">{s.value}</p>
              <p className="text-xs text-muted-foreground">{s.label}</p>
            </div>
          ))}
        </div>

        {/* Valuation estimate (always visible) */}
        <div className="border border-foreground/10 p-5 mb-6">
          <h2 className="text-sm font-semibold mb-4">Valuation Estimate</h2>
          <div className="flex items-end gap-8 mb-4">
            <div>
              <p className="text-xs text-muted-foreground mb-1">Bear case</p>
              <p className="text-2xl font-display text-red-600">{fmt(valRange.low)}</p>
            </div>
            <div className="text-center">
              <p className="text-xs text-muted-foreground mb-1">Base case</p>
              <p className="text-3xl font-display">{fmt(valRange.mid)}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-muted-foreground mb-1">Bull case</p>
              <p className="text-2xl font-display text-green-600">{fmt(valRange.high)}</p>
            </div>
          </div>
          <p className="text-xs text-muted-foreground leading-relaxed">
            Based on comparable pre-seed {startup.stage === "Seed" ? "seed" : "pre-seed"} rounds in the sector,
            GitHub traction metrics, MRR trajectory, and team composition. Bear case assumes competitive
            incumbents block growth. Bull case assumes one enterprise contract closes within 6 months.
          </p>
        </div>

        {/* PAYWALL */}
        {!unlocked ? (
          <div className="relative border border-foreground/20 overflow-hidden">
            {/* Blurred preview */}
            <div className="blur-sm pointer-events-none select-none p-6 space-y-6 opacity-60">
              <div className="h-48 bg-foreground/5 rounded" />
              <div className="h-48 bg-foreground/5 rounded" />
              <div className="h-32 bg-foreground/5 rounded" />
            </div>

            {/* Paywall overlay */}
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-background/90 backdrop-blur-sm p-8 text-center">
              <Lock className="w-8 h-8 text-muted-foreground mb-4" />
              <h3 className="text-xl font-display mb-2">Full report — 0.05 XRP</h3>
              <p className="text-sm text-muted-foreground mb-6 max-w-sm">
                Pay once via XRPL to unlock the complete deep-dive: commit charts, contributor breakdown,
                language distribution, social growth, adversarial audit, and full reasoning.
              </p>
              <div className="flex items-center gap-4 mb-6 text-xs text-muted-foreground">
                {["GitHub activity charts", "Contributor breakdown", "Adversarial audit full findings", "Social metrics over time"].map((item) => (
                  <div key={item} className="flex items-center gap-1">
                    <Check className="w-3 h-3 text-green-500" />
                    {item}
                  </div>
                ))}
              </div>
              <button
                onClick={handleUnlock}
                disabled={paying}
                className="px-8 py-3 bg-foreground text-background text-sm font-bold hover:bg-foreground/90 transition-colors disabled:opacity-60 flex items-center gap-2"
              >
                {paying ? (
                  <>
                    <div className="w-3.5 h-3.5 border-2 border-background/40 border-t-background rounded-full animate-spin" />
                    Processing via XRPL...
                  </>
                ) : (
                  "Unlock for $0.05 →"
                )}
              </button>
              <p className="text-xs text-muted-foreground mt-3 font-mono">Paid via XRPL · 0.05 XRP · instant access</p>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="flex items-center gap-2 bg-green-50 border border-green-200 px-4 py-2">
              <Check className="w-4 h-4 text-green-500" />
              <span className="text-sm text-green-700">Unlocked — 0.05 XRP paid via XRPL</span>
            </div>

            {/* GitHub activity */}
            <div className="border border-foreground/10 p-5">
              <div className="flex items-center gap-2 mb-4">
                <Github className="w-4 h-4" />
                <h2 className="text-sm font-semibold">GitHub Activity — Commit Frequency</h2>
              </div>
              <ResponsiveContainer width="100%" height={180}>
                <BarChart data={startup.commitFrequency} margin={{ top: 4, right: 4, bottom: 0, left: -20 }}>
                  <XAxis dataKey="month" tick={{ fontSize: 11 }} />
                  <YAxis tick={{ fontSize: 11 }} />
                  <Tooltip
                    formatter={(v: number, name: string) => [v, name === "commits" ? "Commits" : name]}
                    contentStyle={{ fontSize: 11 }}
                  />
                  <Bar dataKey="commits" fill="currentColor" fillOpacity={0.8} radius={[2, 2, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Lines: additions vs deletions */}
            <div className="border border-foreground/10 p-5">
              <h2 className="text-sm font-semibold mb-4">Code Changes — Additions vs Deletions</h2>
              <ResponsiveContainer width="100%" height={160}>
                <LineChart data={startup.commitFrequency} margin={{ top: 4, right: 4, bottom: 0, left: -20 }}>
                  <XAxis dataKey="month" tick={{ fontSize: 11 }} />
                  <YAxis tick={{ fontSize: 11 }} />
                  <Tooltip contentStyle={{ fontSize: 11 }} />
                  <Line type="monotone" dataKey="additions" stroke="#22c55e" strokeWidth={1.5} dot={false} name="Additions" />
                  <Line type="monotone" dataKey="deletions" stroke="#ef4444" strokeWidth={1.5} dot={false} name="Deletions" />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* Language distribution + contributor */}
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="border border-foreground/10 p-5">
                <h2 className="text-sm font-semibold mb-4">Language Distribution</h2>
                <div className="flex items-center gap-4">
                  <PieChart width={120} height={120}>
                    <Pie data={langData} cx={55} cy={55} innerRadius={30} outerRadius={55} dataKey="value" paddingAngle={2}>
                      {langData.map((_, i) => (
                        <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />
                      ))}
                    </Pie>
                  </PieChart>
                  <div className="space-y-1.5">
                    {langData.map((lang, i) => (
                      <div key={lang.name} className="flex items-center gap-2 text-xs">
                        <div className="w-2.5 h-2.5 rounded-sm" style={{ background: PIE_COLORS[i] }} />
                        <span className="text-muted-foreground w-20">{lang.name}</span>
                        <span className="font-mono font-semibold">{lang.value}%</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="border border-foreground/10 p-5">
                <h2 className="text-sm font-semibold mb-4">Contributor Breakdown</h2>
                <div className="space-y-3">
                  {[
                    { name: startup.founder.split(" ")[0], commits: 312, pct: 37 },
                    { name: "jsmith", commits: 198, pct: 23 },
                    { name: "k_dev", commits: 145, pct: 17 },
                    { name: "others", commits: 192, pct: 23 },
                  ].map((c) => (
                    <div key={c.name} className="flex items-center gap-3 text-xs">
                      <span className="font-mono w-16 text-muted-foreground truncate">{c.name}</span>
                      <div className="flex-1 h-1.5 bg-foreground/10 rounded-full overflow-hidden">
                        <div className="h-full bg-foreground/60 rounded-full" style={{ width: `${c.pct}%` }} />
                      </div>
                      <span className="font-mono font-semibold w-8 text-right">{c.commits}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Social metrics */}
            <div className="border border-foreground/10 p-5">
              <h2 className="text-sm font-semibold mb-4">Social Metrics Over Time</h2>
              <ResponsiveContainer width="100%" height={160}>
                <LineChart data={SOCIAL_DATA} margin={{ top: 4, right: 4, bottom: 0, left: -20 }}>
                  <XAxis dataKey="month" tick={{ fontSize: 11 }} />
                  <YAxis yAxisId="left" tick={{ fontSize: 11 }} />
                  <YAxis yAxisId="right" orientation="right" tick={{ fontSize: 11 }} />
                  <Tooltip contentStyle={{ fontSize: 11 }} />
                  <Line yAxisId="left" type="monotone" dataKey="followers" stroke="#1a1a1a" strokeWidth={1.5} dot={false} name="Followers" />
                  <Line yAxisId="right" type="monotone" dataKey="mentions" stroke="#888" strokeWidth={1.5} dot={false} name="Mentions" />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* Adversarial audit full findings */}
            <div className="border border-foreground/10 p-5">
              <div className="flex items-center gap-2 mb-4">
                <Shield className="w-4 h-4" />
                <h2 className="text-sm font-semibold">Adversarial Audit — Full Findings</h2>
              </div>

              {startup.redFlags.length > 0 ? (
                <div className="space-y-3 mb-4">
                  {startup.redFlags.map((f, i) => (
                    <div key={i} className="flex gap-3 bg-red-50 border border-red-100 p-3">
                      <AlertTriangle className="w-4 h-4 text-red-500 shrink-0 mt-0.5" />
                      <div>
                        <p className="text-sm font-semibold text-red-700">{f}</p>
                        <p className="text-xs text-red-600 mt-1">
                          This pattern has been observed in 23% of startups that fail within 18 months.
                          Recommend direct follow-up with the team.
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="bg-green-50 border border-green-100 p-4 mb-4">
                  <div className="flex items-center gap-2 mb-1">
                    <Check className="w-4 h-4 text-green-500" />
                    <p className="text-sm font-semibold text-green-700">No critical red flags found</p>
                  </div>
                  <p className="text-xs text-green-600">
                    Commit history is clean, contributor diversity is healthy, and no suspicious patterns were detected.
                  </p>
                </div>
              )}

              <div className="grid sm:grid-cols-2 gap-3">
                {[
                  { icon: TrendingUp, color: "text-green-500", label: "Commit consistency", value: "Above average — 8+ months sustained activity" },
                  { icon: TrendingUp, color: "text-green-500", label: "Dependency health", value: "4 outdated packages · 0 critical CVEs" },
                  { icon: TrendingDown, color: "text-amber-500", label: "Bus factor", value: "2 — dangerously low for this stage" },
                  { icon: TrendingUp, color: "text-green-500", label: "License compliance", value: "MIT — clean, no viral licenses" },
                ].map((item) => (
                  <div key={item.label} className="border border-foreground/10 p-3">
                    <div className="flex items-center gap-2 mb-1">
                      <item.icon className={`w-3.5 h-3.5 ${item.color}`} />
                      <p className="text-xs font-semibold">{item.label}</p>
                    </div>
                    <p className="text-xs text-muted-foreground">{item.value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* CTA */}
            <div className="flex gap-3">
              <Link
                href={`/market/${startup.id}`}
                className="flex-1 py-3 bg-foreground text-background text-sm font-semibold text-center hover:bg-foreground/90 transition-colors"
              >
                Go to prediction market →
              </Link>
              <button
                onClick={handleCopy}
                className="px-6 py-3 border border-foreground/20 text-sm hover:bg-foreground/5 transition-colors flex items-center gap-2"
              >
                <Share2 className="w-4 h-4" />
                {copied ? "Copied!" : "Share report"}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
