import { createHash } from "node:crypto";
import type { SAFEDocument } from "./types.js";

/**
 * Generate a SAFE (Simple Agreement for Future Equity) document from parameters.
 * Returns the full text and its SHA256 hash (for on-chain anchoring).
 *
 * Based on the Y Combinator post-money SAFE template, adapted for
 * cross-chain settlement between XRPL and Base.
 */
export function generateSAFEDocument(params: {
  companyName: string;
  valuationCapUSD: number;
  discountRateBps: number;
  investmentAmountUSD: number;
  founderXrplAddress: string;
  investorCount: number;
  consensusValuationM: number;
  reportSummary: string;
  governingLaw: string;
  disputeResolution: string;
}): SAFEDocument {
  const discountPercent = params.discountRateBps / 100;
  const date = new Date().toISOString().split("T")[0];

  const text = `SIMPLE AGREEMENT FOR FUTURE EQUITY (SAFE)
===========================================

Company: ${params.companyName}
Date: ${date}
Platform: Lapis AI-Powered Valuation & Settlement

THIS CERTIFIES THAT in exchange for the payment by the Investor(s) of the
Investment Amount set forth below, ${params.companyName} (the "Company")
hereby issues to the Investor(s) the right to certain shares of the Company's
equity, subject to the terms set forth herein.

TERMS
-----

Valuation Cap:        $${params.valuationCapUSD.toLocaleString()} USD
Discount Rate:        ${discountPercent}%
Investment Amount:    $${params.investmentAmountUSD.toLocaleString()} USD
Number of Investors:  ${params.investorCount}

AI VALUATION ANALYSIS
---------------------

Consensus Valuation:  $${params.consensusValuationM}M USD
Analysis Summary:     ${params.reportSummary}

This valuation was determined through a combination of AI analysis (powered by
Claude) and crowd prediction market consensus on the Lapis platform. The AI
agent analyzed the Company's GitHub repository, team composition, traction
metrics, and social presence to generate an initial score, which was then
refined through market participation.

CROSS-CHAIN SETTLEMENT
-----------------------

Settlement Ledger:         XRPL (XRP Ledger)
Equity Token Standard:     MPT (Multi-Purpose Token)
Founder XRPL Address:      ${params.founderXrplAddress}
Legal Anchor Chain:        Base (MetaLEX pattern)

The equity represented by this SAFE is tokenized as an MPT on the XRP Ledger.
The MPT metadata contains a reference to this agreement's on-chain anchor on
Base, creating a bidirectional cross-chain link between the legal agreement
and the equity token.

Vesting is enforced via XRPL EscrowCreate with PREIMAGE-SHA-256 crypto-
conditions. The Lapis AI agent acts as trustee, holding fulfillment preimages
and releasing escrows when conversion conditions are met.

CONVERSION
----------

This SAFE will convert into equity shares upon the occurrence of an Equity
Financing round, a Liquidity Event, or a Dissolution Event, as defined in
the standard Y Combinator post-money SAFE terms.

Upon conversion:
1. The AI agent verifies the conversion event
2. Agent calls EscrowFinish on XRPL with the fulfillment preimage
3. Vested equity shares are released to the Investor's XRPL address
4. This agreement is marked as Settled on Base

GOVERNING LAW
-------------

This agreement shall be governed by the laws of ${params.governingLaw}.

DISPUTE RESOLUTION
------------------

${params.disputeResolution}

SIGNATURES
----------

This agreement is signed cryptographically by the parties through on-chain
transactions on both the XRP Ledger and Base networks. The deployment
transaction on Base constitutes the Company's signature. Investor confirmation
transactions constitute Investor signatures.

---
Generated by Lapis (https://lapis.ai) on ${date}
Document hash anchored on Base via MetaLEX-pattern contract
`;

  const hash = hashDocument(text);
  return { text, hash };
}

function hashDocument(text: string): `0x${string}` {
  const hash = createHash("sha256").update(text).digest("hex");
  return `0x${hash}` as `0x${string}`;
}
